name: ElectricField
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.6.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attr=2.5.1
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.1
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.6.15
  - cffi=1.15.1
  - click=8.1.3
  - colorama=0.4.5
  - dash=2.6.0
  - dash-bootstrap-components=1.2.0
  - dbus=1.13.6
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.9.1
  - expat=2.4.8
  - fftw=3.3.10
  - flask=2.1.3
  - flask-compress=1.12
  - flit-core=3.7.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.72.1
  - glib-tools=2.72.1
  - gst-plugins-base=1.20.3
  - gstreamer=1.20.3
  - icu=70.1
  - importlib-metadata=4.11.4
  - importlib_resources=5.9.0
  - ipykernel=6.15.1
  - ipython=8.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.7.1
  - itsdangerous=2.1.2
  - jack=1.9.18
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.7.2
  - jupyter=1.0.0
  - jupyter_client=7.3.4
  - jupyter_console=6.4.4
  - jupyter_core=4.11.1
  - jupyterlab_pygments
  - jupyterlab_widgets
  - keyutils=1.6.1
  - krb5=1.19.3
  - ld_impl_linux-64=2.36.1
  - libblas=3.9.0
  - libcap=2.64
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.3.3
  - libdb=6.2.32
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.4.2
  - libflac=1.3.4
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.72.1
  - libgomp=12.1.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.20
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=14.4
  - libsndfile=1.0.31
  - libsodium=1.0.18
  - libstdcxx-ng=12.1.0
  - libtool=2.4.6
  - libudev1=249
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.14
  - libzlib=1.2.12
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mysql-common=8.0.29
  - mysql-libs=8.0.29
  - nbclient=0.6.6
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.4.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - notebook=6.4.12
  - nspr=4.32
  - nss=3.78
  - numpy=1.23.1
  - openssl=1.1.1q
  - packaging=21.3
  - pandoc=2.18
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.2
  - plotly=5.9.0
  - ply=3.11
  - portaudio=19.6.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.30
  - prompt_toolkit=3.0.30
  - psutil=5.9.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=14.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.12.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.1
  - python=3.10.5
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.1
  - python_abi=3.10
  - pyzmq=23.2.0
  - qt-main=5.15.4
  - qtconsole=5.3.1
  - qtconsole-base=5.3.1
  - qtpy=2.1.0
  - readline=8.1.2
  - send2trash=1.8.0
  - setuptools=63.2.0
  - sip=6.6.2
  - six=1.16.0
  - soupsieve=2.3.2.post1
  - sqlite=3.39.2
  - stack_data=0.3.0
  - tenacity=8.0.1
  - terminado=0.15.0
  - tinycss2=1.1.1
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - tqdm=4.64.0
  - traitlets=5.3.0
  - tzdata=2022a
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.2.0
  - wheel=0.37.1
  - widgetsnbextension
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil
  - xcb-util-wm
  - xorg-libxau
  - xorg-libxdmcp
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - pandas==1.4.3
    - pytz==2022.1
